language: cpp
compiler:
  - clang
env:
  matrix: 
    - JULIAVERSION="juliareleases" 
    - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("NLP"))`); Pkg.pin("NLP"); Pkg.resolve()'
  - julia -e 'using NLP; @assert isdefined(:NLP); @assert typeof(NLP) === Module'
  - julia --code-coverage ./test/runtests.jl
after_success:
  - julia -e 'cd(Pkg.dir("NLP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'